"""initial schema

Revision ID: 0d78f3581ca2
Revises: 
Create Date: 2026-09-05 20:22:53.446206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d78f3581ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_key', sa.String(length=64), nullable=False),
    sa.Column('pattern_name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('pattern_strength', sa.Float(), nullable=False),
    sa.Column('raw_ohlcv', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candlestick_detections_candle_timestamp'), 'candlestick_detections', ['candle_timestamp'], unique=False)
    op.create_index(op.f('ix_candlestick_detections_pattern_key'), 'candlestick_detections', ['pattern_key'], unique=False)
    op.create_index(op.f('ix_candlestick_detections_symbol'), 'candlestick_detections', ['symbol'], unique=False)
    op.create_index(op.f('ix_candlestick_detections_timeframe'), 'candlestick_detections', ['timeframe'], unique=False)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_9', sa.Float(), nullable=True),
    sa.Column('ema_21', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('avg_volume_20', sa.Float(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.Column('recent_high_20', sa.Float(), nullable=True),
    sa.Column('recent_low_20', sa.Float(), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('resistance_level', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('structure', sa.String(length=20), nullable=True),
    sa.Column('breakout', sa.String(length=20), nullable=True),
    sa.Column('consolidation', sa.Boolean(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_snapshots_candle_timestamp'), 'indicator_snapshots', ['candle_timestamp'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_symbol'), 'indicator_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_timeframe'), 'indicator_snapshots', ['timeframe'], unique=False)
    op.create_table('news_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_cache_category'), 'news_cache', ['category'], unique=False)
    op.create_index(op.f('ix_news_cache_published_at'), 'news_cache', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_cache_symbol'), 'news_cache', ['symbol'], unique=False)
    op.create_table('system_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configuration_key'), 'system_configuration', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', name='uq_user_channel')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('indicator_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_key', sa.String(length=64), nullable=False),
    sa.Column('pattern_name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=False),
    sa.Column('target_3', sa.Float(), nullable=False),
    sa.Column('risk_per_share', sa.Float(), nullable=False),
    sa.Column('reward_to_t1', sa.Float(), nullable=False),
    sa.Column('reward_to_t2', sa.Float(), nullable=False),
    sa.Column('reward_to_t3', sa.Float(), nullable=False),
    sa.Column('rr_t1', sa.Float(), nullable=False),
    sa.Column('rr_t2', sa.Float(), nullable=False),
    sa.Column('rr_t3', sa.Float(), nullable=False),
    sa.Column('risk_methodology', sa.String(length=512), nullable=False),
    sa.Column('technical_confirmations', sa.JSON(), nullable=False),
    sa.Column('news_context', sa.JSON(), nullable=False),
    sa.Column('market_context', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['candlestick_detections.id'], ),
    sa.ForeignKeyConstraint(['indicator_snapshot_id'], ['indicator_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_candle_timestamp'), 'signals', ['candle_timestamp'], unique=False)
    op.create_index(op.f('ix_signals_detected_at'), 'signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_signals_fingerprint'), 'signals', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_signals_timeframe'), 'signals', ['timeframe'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rendered_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_signal_id'), 'alert_history', ['signal_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=True),
    sa.Column('min_score_override', sa.Integer(), nullable=True),
    sa.Column('enabled_patterns', sa.JSON(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_symbol'), 'watchlist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_symbol'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_alert_history_signal_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_signals_timeframe'), table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_fingerprint'), table_name='signals')
    op.drop_index(op.f('ix_signals_detected_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_candle_timestamp'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configuration_key'), table_name='system_configuration')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_news_cache_symbol'), table_name='news_cache')
    op.drop_index(op.f('ix_news_cache_published_at'), table_name='news_cache')
    op.drop_index(op.f('ix_news_cache_category'), table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index(op.f('ix_indicator_snapshots_timeframe'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_symbol'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_candle_timestamp'), table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_index(op.f('ix_candlestick_detections_timeframe'), table_name='candlestick_detections')
    op.drop_index(op.f('ix_candlestick_detections_symbol'), table_name='candlestick_detections')
    op.drop_index(op.f('ix_candlestick_detections_pattern_key'), table_name='candlestick_detections')
    op.drop_index(op.f('ix_candlestick_detections_candle_timestamp'), table_name='candlestick_detections')
    op.drop_table('candlestick_detections')
    # ### end Alembic commands ###
